# Generated by Django 3.2.6 on 2021-09-17 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='url',
            unique_together={('original_url', 'user')},
        ),
    ]
